const retailerValidation = {
  // USA RETAILERS
  "Amazon": {
    region: "USA",
    digits: [14, 15, 16],
    startsWith: ["AQ"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.75,
    buyerRate: 0.85,
  },
  "Nike": {
    region: "USA",
    digits: [19],
    startsWith: ["6060"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.70,
    buyerRate: 0.80,
  },
  "Uber": {
    region: "USA",
    digits: [16],
    startsWith: ["6110"],
    pinRequired: false,
    strictPrefix: false,
    sellerRate: 0.77,
    buyerRate: 0.86,
  },
  "DICK’S SPORTING GOODS": {
    region: "USA",
    digits: [19],
    startsWith: ["6006"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.72,
    buyerRate: 0.82,
  },
  "Steam": {
    region: "USA",
    digits: [15],
    startsWith: ["A", "B"],
    pinRequired: false,
    strictPrefix: false,
    sellerRate: 0.70,
    buyerRate: 0.80,
  },
  "Door Dash": {
    region: "USA",
    digits: [16],
    startsWith: ["6109"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.74,
    buyerRate: 0.84,
  },
  "AMC": {
    region: "USA",
    digits: [19],
    startsWith: ["6036", "6366"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.65,
    buyerRate: 0.75,
  },
  "Best Buy": {
    region: "USA",
    digits: [15, 16],
    startsWith: ["6006", "6102"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.78,
    buyerRate: 0.88,
  },
  "PlayStation": {
    region: "USA",
    digits: [12],
    startsWith: [],
    pinRequired: false,
    strictPrefix: false,
    sellerRate: 0.67,
    buyerRate: 0.76,
  },
  "Xbox": {
    region: "USA",
    digits: [25],
    startsWith: [],
    pinRequired: false,
    strictPrefix: false,
    sellerRate: 0.67,
    buyerRate: 0.76,
  },
  "Costco": {
    region: "USA",
    digits: [16],
    startsWith: ["61"],
    pinRequired: true,
    strictPrefix: false,
    sellerRate: 0.80,
    buyerRate: 0.90,
  },


  // UK RETAILERS
  "Uber_UK": {
    region: "UK",
    digits: 16,
    startsWith: ["NAAA"],
    pinRequired: false,
    sellerRate: 0.77,
    buyerRate: 0.86,
  },
  "Currys": {
    region: "UK",
    digits: 19,
    startsWith: ["5045075659"],
    pinRequired: true,
    sellerRate: 0.76,
    buyerRate: 0.85,
  },
  "John Lewis": {
    region: "UK",
    digits: 19,
    startsWith: ["63719600"],
    pinRequired: true,
    sellerRate: 0.78,
    buyerRate: 0.87,
  },
  "Apple": {
    region: "UK",
    digits: 16,
    startsWith: ["X"],
    pinRequired: false,
    sellerRate: 0.79,
    buyerRate: 0.88,
  },
  "Deliveroo": {
    region: "UK",
    digits: 16,
    startsWith: ["NAAQ"],
    pinRequired: false,
    sellerRate: 0.75,
    buyerRate: 0.84,
  },
  "Just Eat": {
    region: "UK",
    digits: 12,
    startsWith: ["C"],
    pinRequired: false,
    sellerRate: 0.75,
    buyerRate: 0.84,
  },
  "Halfords": {
    region: "UK",
    digits: 19,
    startsWith: ["50450758"],
    pinRequired: true,
    sellerRate: 0.70,
    buyerRate: 0.79,
  },
  "ASDA": {
    region: "UK",
    digits: 16,
    startsWith: ["63"],
    pinRequired: true,
    sellerRate: 0.72,
    buyerRate: 0.81,
  },
  "PlayStation_UK": {
    region: "UK",
    digits: 12,
    startsWith: [],
    pinRequired: false,
    sellerRate: 0.67,
    buyerRate: 0.76,
  },

  // CANADA RETAILERS
  "Amazon_CA": {
    region: "Canada",
    digits: 15,
    startsWith: [],
    pinRequired: true,
    sellerRate: 0.75,
    buyerRate: 0.85,
  }
};

module.exports = { retailerValidation };
